image: "python:3.6"

before_script:
  - python3 --version
  - pip install flake8 lizard

stages:
  - analysis
  - test

analysis:
  - stage: analysis
  - script:
  - flake8
  - lizard

test:
  - stage: test
  - script:
  - python3 unit_test.py
