image: "python:3.6"

before_script:
  - python3 --version
  - pip3 install lizard flake8

analyze:
  script: flake8 && lizard

test:
  script:
    - python3 unit_test.py <<< k
    - python3 unit_test.py <<< o
    - python3 unit_test.py <<< w
